// export const CREED: string[] = ["I believe in God,", "the Father almighty,", "Creator of heaven and earth,", "and in Jesus Christ, his only Son, our Lord,", "who was conceived by the Holy Spirit,", "born of the Virgin Mary,", "suffered under Pontius Pilate,", "was crucified, died and was buried;", "he descended into hell;", "on the third day he rose again from the dead;", "he ascended into heaven,", "and is seated at the right hand of God the Father almighty;", "from there he will come to judge the living and the dead.", "I believe in the Holy Spirit,", "the holy catholic Church,", "the communion of saints,", "the forgiveness of sins,", "the resurrection of the body,", "and life everlasting.", "Amen."]
export const CREED: string[] = ["I believe in God, the Father almighty,\nCreator of heaven and earth,\nand in Jesus Christ, his only Son, our Lord,\nwho was conceived by the Holy Spirit,\nborn of the Virgin Mary,\nsuffered under Pontius Pilate,\nwas crucified, died and was buried;\nhe descended into hell;\non the third day he rose again from the dead;\nhe ascended into heaven,\nand is seated at the right hand of God the Father almighty;\nfrom there he will come to judge the living and the dead.\nI believe in the Holy Spirit,\nthe holy catholic Church,\nthe communion of saints,\nthe forgiveness of sins,\nthe resurrection of the body,\nand life everlasting.\nAmen."]

export const SIGN_OF_CROSS: string = "In the name of The Father, The Son, and The Holy Spirit. Amen."

export const OUR_FATHER: string[] = ["Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth, as it is in heaven.", "Give us this day our daily bread; and forgive our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil.", "Amen."]

export const HAIL_MARY: string[] = ["Hail Mary, full of grace; the Lord is with thee; blessed art thou among women, and blessed is the fruit of your womb, Jesus.", "Holy, Mary, Mother of God, pray for us sinners, now and at the hour of our death.", "Amen."]

export const GLORY_BE : string[] = ["Glory be to the Father, and to the Son, and to the Holy Spirit.", "As it was in the beginning, is now, and ever shall be, world without end.", "Amen."]

export const FATIMA_PRAYER: string = "O my Jesus, forgive us our sins, save us from the fires of hell. Lead all souls to Heaven, especially those in most need of thy mercy."

export const HAIL_HOLY_QUEEN: string[] = ["Hail Holy Queen, Mother of Mercy, our Life, our Sweetness, and our hope. To thee we cry, poor banished children of Eve. To thee we send up our sighs, mourning and weeping in this vale of tears.", "Turn then most gracious advocate, Thine eyes of mercy toward us, and after this, our exile, show unto us, the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary.", "Pray for us O Holy Mother of God,", "That we may be made worthy of the promises of Christ."]

export const FINAL_PRAYER: string[] = ["Let us pray.", "O God, whose only begotten Son, by His life, death, and resurrection, has purchased for us the rewards of eternal life, grant, we beseech Thee, that meditating upon these mysteries of the Most Holy Rosary of the Blessed Virgin Mary, we may imitate what they contain and obtain what they promise, through the same Christ Our Lord.", "Amen."]

export const ST_MICHAEL: string[] = ["Saint Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil.", "May God rebuke him, we humbly pray; And do thou, O Prince of the Heavenly Host, by the power of God, cast into hell Satan and all evil spirits who prowl about the world seeking the ruin of souls.", "Amen."]
